name: lint

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 16 * *'
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run the sh-checker
        uses: luizm/action-sh-checker@master
        env:
          SHFMT_OPTS: --simplify --keep-padding
        with:
          sh_checker_checkbashisms_enable: true
          sh_checker_shfmt_disable: true
