name: tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 16 * *'
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  with-default-options:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Execute this action
        uses: ./

      - run: trivy --version

  with-specific-version:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        cache: [ true, false ]

    steps:
      - uses: actions/checkout@v4

      - name: Execute this action
        uses: ./
        with:
          version: 'v0.64.0'
          cache: ${{ matrix.cache }}

      - run: trivy --version

